version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  chatapp:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=chatdb;Username=chatuser;Password=chatpass
      - Jwt__Key=super_secret_key_1234567890_abcdefghijklmno!
      - Jwt__Issuer=yourapp.com
      - Jwt__Audience=yourapp.com
      - Redis__ConnectionString=redis:6379

volumes:
  postgres_data: